import arcade

TILE_WIDTH = 17
TILE_HEIGHT = 9
TILE_SIZE = 32
SCREEN_TITLE = "1928"
SPEED = 5
TILE_SCALING = 2

WINDOW_WIDTH = TILE_WIDTH * TILE_SIZE * TILE_SCALING
WINDOW_HEIGHT = TILE_HEIGHT * TILE_SIZE * TILE_SCALING

D_UP = 0
D_RIGHT = 1
D_DOWN = 2
D_LEFT = 3

UP="UP"
RIGHT="RIGHT"
DOWN="DOWN"
LEFT="LEFT"

DIRECTIONS = [UP, RIGHT, DOWN, LEFT]
DIRECTION_KEYS = {
    UP: arcade.key.UP,
    RIGHT: arcade.key.RIGHT,
    DOWN: arcade.key.DOWN,
    LEFT: arcade.key.LEFT
}